dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install --progress-bar off -r dev-requirements.txt

script:
  - python3 -m pytest test/
  - pycodestyle --max-line-length=80 --count --statistics .
  - mypy evolution/ --disallow-incomplete-defs
  - mypy examples/ --disallow-incomplete-defs
