dist: xenial
language: python
python: 3.7
install:
  - pip install --upgrade pip
  - pip install --progress-bar off -r requirements.txt

script:
  - pytest
  - pycodestyle --max-line-length=80 --count --statistics .
  - mypy toolbox/ --disallow-incomplete-defs